name: CI and tarball generation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

env:
  LANG: en_US.UTF-8
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-all:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
    - name: Install build dependencies
      run: apt-get update -y && apt-get install -y meson build-essential libgtkmm-3.0-dev golang gcc-arm-none-eabi libnewlib-arm-none-eabi python3 git gstreamer1.0-gtk3 gstreamer1.0-plugins-good libhidapi-dev libgstreamer1.0-dev
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build bootloader
      working-directory: fw/boot
      run: make -j $(nproc)
    - name: Build firmware
      working-directory: fw/usbkvm
      run: make -j $(nproc)
    - name: Build app
      working-directory: app
      run: |
        mkdir ../build-app
        meson setup ../build-app
        ninja -C ../build-app
