name: Build Windows binaries

on:
  push:
    branches:
      - '**'
      - '!appveyor-*'
      - '!freebsd-*'
      - '!pr-review*'
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Check tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "Building tag ${{ github.ref }}"
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-gtkmm3
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-python
          mingw-w64-x86_64-gstreamer
          mingw-w64-x86_64-gst-plugin-gtk
          mingw-w64-x86_64-gst-plugins-bad
          mingw-w64-x86_64-gst-plugins-good
          mingw-w64-x86_64-hidapi
          mingw-w64-x86_64-go
          mingw-w64-x86_64-arm-none-eabi-gcc
          make
          git
          zip
          dos2unix
    - name: Build bootloader
      shell: msys2 {0}
      working-directory: fw/boot
      run: make -j $(nproc)
    - name: Build firmware
      shell: msys2 {0}
      working-directory: fw/usbkvm
      run: make -j $(nproc)
    - name: Build app
      shell: msys2 {0}
      working-directory: app
      run: |
        meson setup build
        meson compile -C build
    - name: Make dist
      shell: msys2 {0}
      working-directory: app
      run: ./make_bindist.sh
    - name: set artifact name
      shell: msys2 {0}
      run: echo "artifact_name=usbkvm-win64-$(date +%Y-%m-%d-%H%M)-$(echo ${{ github.ref_name }} | tr / -)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}
        path: app/dist/*.zip
